version: "2"
services:
  node:
    image: "sberthu/nodepm2"
    #build: .
    user: "root"
    restart: always
    environment:
      - "NODE_ENV=${NODE_ENV}"
      - "REDIS_PREFIX=${REDIS_PREFIX}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "MIN_USER_ID=${MIN_USER_ID}"
      - "NODE_PORT=${NODE_PORT}"
    volumes:
      - ./app:/home/node/app/
      - './.bashrc:/root/.bashrc'
      - ./init:/init
    #pas de port sortant, uniquement appele depuis le reseau sberthu/network par krakend
    #ports:
    #  - "8300:8000"
    working_dir: "/init"
    command: /bin/sh -c "/init/./start.sh"
    networks:
      - "sberthu/network"
networks:        
  "sberthu/network":
    external: true          

